version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/docs"]
      interval: 20s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastapi_guide
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_guide"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"

volumes:
  postgres_data:



